"""tokenpak.vault.retrieval — re-export shim for retrieval functions."""
from tokenpak.vault.search import (
    inject_retrieved_context,
    sort_retrieval_results,
    compute_final_score,
    extract_must_hit_terms,
    all_must_hits_found,
    measure_injection_consistency,
    COVERAGE_OK,
    COVERAGE_STRONG,
    _BOOST_PATH,
    _BOOST_RECENCY,
    _BOOST_SYMBOL,
    _PENALTY_NOISE,
    _PENALTY_STALE,
    _W_BM25,
    _W_META,
    _W_SEM,
    chunks_contain_term,
    compute_coverage_score,
    interpret_coverage,
    score_and_sort,
)

__all__ = [
    "inject_retrieved_context",
    "sort_retrieval_results",
    "compute_final_score",
    "extract_must_hit_terms",
    "all_must_hits_found",
    "measure_injection_consistency",
    "COVERAGE_OK",
    "COVERAGE_STRONG",
    "_BOOST_PATH",
    "_BOOST_RECENCY",
    "_BOOST_SYMBOL",
    "_PENALTY_NOISE",
    "_PENALTY_STALE",
    "_W_BM25",
    "_W_META",
    "_W_SEM",
    "chunks_contain_term",
    "compute_coverage_score",
    "interpret_coverage",
    "score_and_sort",
]
