"""tokenpak.errors — backward-compat shim.

All error classes have moved to tokenpak.infrastructure.error_handling.
"""

from tokenpak.infrastructure.error_handling import (
    TokenPakError,
    ConfigError,
    ConfigValidationError,
    MissingConfigError,
    InvalidConfigFileError,
    NetworkConnectionError as ConnectionError,
    ProviderConnectionError,
    RequestTimeoutError as TimeoutError,
    AuthError,
    AuthenticationError,
    InvalidAPIKeyError,
    MissingAPIKeyError,
    RateLimitError,
    CacheError,
    CacheCorruptedError,
    ProviderError,
    ProviderUnknownError,
    InternalError,
    TokenPakNotImplementedError,
    NotImplementedError,  # noqa: A001
    ProxyStartupError,
    PortInUseError,
    PermissionDeniedError,
    MissingDependencyError,
    LiteLLMError,
    ValidationError,
    CLIError,
    UnknownCommandError,
    format_error,
)

__all__ = [
    "TokenPakError",
    "ConfigError",
    "ConfigValidationError",
    "MissingConfigError",
    "InvalidConfigFileError",
    "ConnectionError",
    "ProviderConnectionError",
    "TimeoutError",
    "AuthError",
    "AuthenticationError",
    "InvalidAPIKeyError",
    "MissingAPIKeyError",
    "RateLimitError",
    "CacheError",
    "CacheCorruptedError",
    "ProviderError",
    "ProviderUnknownError",
    "InternalError",
    "TokenPakNotImplementedError",
    "NotImplementedError",
    "ProxyStartupError",
    "PortInUseError",
    "PermissionDeniedError",
    "MissingDependencyError",
    "LiteLLMError",
    "ValidationError",
    "CLIError",
    "UnknownCommandError",
    "format_error",
]
