"""Bidirectional pickle rollback-compatibility probes for domain-local DTOs.

Five domain-local trace/recommendation DTO classes keep a stable historical
runtime identity (module path + class name). Two invariants protect rollback
between this tree and the prior public release head
``e080170ba76b9164d2757b9afc3d6b27f3af4850``:

* base -> new: pickles produced at the prior release load on this tree.
  The fixtures under ``tests/fixtures/pickle_compat/`` were generated by
  executing the prior release's module sources (all stdlib-only) in an
  isolated interpreter and pickling representative instances at protocol 2.
  The ``proxy_server_stage_trace.pkl`` fixture covers the prior release's
  field-identical ``tokenpak.proxy.server.StageTrace`` definition; it was
  derived from the tracing fixture by rewriting the module string inside the
  protocol-2 GLOBAL opcode and is opcode-verified below before use.

* new -> base: pickles produced by this tree reference only global names
  that exist at the prior release, so the prior code can still load them
  after a rollback.
"""

from __future__ import annotations

import pickle
import pickletools
from pathlib import Path

import pytest

from tokenpak.proxy import tracing as proxy_tracing
from tokenpak.services.optimization import trace as service_trace
from tokenpak.telemetry import pipeline_trace as telemetry_trace
from tokenpak.telemetry import recommendations as telemetry_rec

FIXTURE_DIR = Path(__file__).parent / "fixtures" / "pickle_compat"

# Every class global that pickles of these DTOs may reference. Each pair
# resolves at the prior public release head as well as on this tree.
HISTORICAL_DTO_GLOBALS = {
    ("tokenpak.services.optimization.trace", "StageTrace"),
    ("tokenpak.services.optimization.trace", "OptimizationTrace"),
    ("tokenpak.proxy.tracing", "StageTrace"),
    ("tokenpak.proxy.server", "StageTrace"),
    ("tokenpak.telemetry.pipeline_trace", "StageTrace"),
    ("tokenpak.telemetry.recommendations", "Recommendation"),
}

# Plumbing globals the stdlib pickler may emit for plain-object reduction
# at old protocols. All exist unchanged at the prior release (stdlib).
STDLIB_PICKLE_GLOBALS = {
    ("copy_reg", "_reconstructor"),
    ("copyreg", "_reconstructor"),
    ("__builtin__", "object"),
    ("builtins", "object"),
}


def _referenced_globals(data: bytes) -> list[tuple[str, str]]:
    """Return every (module, name) global reference inside a pickle.

    GLOBAL carries module/name inline. STACK_GLOBAL consumes the two most
    recently pushed strings, which may be fresh string pushes or memo
    retrievals (the pickler memoizes module strings and reuses them via
    *GET for later classes from the same module), so string pushes and the
    memo are both tracked.
    """
    refs: list[tuple[str, str]] = []
    pushed: list[str] = []  # string values pushed onto the stack, in order
    memo: dict[object, str] = {}
    memoize_count = 0
    pending_string = None  # last op pushed this string (still top of stack)
    for op, arg, _pos in pickletools.genops(data):
        name = op.name
        if name in ("SHORT_BINUNICODE", "BINUNICODE", "BINUNICODE8", "UNICODE"):
            pushed.append(arg)
            pending_string = arg
            continue
        if name == "MEMOIZE":
            # Implicit memo: sequential index, memoizes top of stack.
            if pending_string is not None:
                memo[memoize_count] = pending_string
            memoize_count += 1
            continue  # MEMOIZE does not pop; the string stays on top
        if name in ("PUT", "BINPUT", "LONG_BINPUT"):
            if pending_string is not None:
                memo[arg] = pending_string
            continue  # PUT does not pop either
        if name in ("GET", "BINGET", "LONG_BINGET"):
            if arg in memo:
                pushed.append(memo[arg])
                pending_string = memo[arg]
                continue
        elif name == "GLOBAL":
            module, gname = arg.split(" ")
            refs.append((module, gname))
        elif name == "STACK_GLOBAL":
            refs.append((pushed[-2], pushed[-1]))
        pending_string = None
    return refs


def _new_instances():
    svc_stage = service_trace.StageTrace(
        name="cache", eligible=True, skip_reason="", applied=False, duration_ms=0.5, detail="probe"
    )
    svc_trace = service_trace.OptimizationTrace(
        request_id="probe-1", mode="observe", started_at=1234.5, body_bytes_in=10, body_bytes_out=10
    )
    svc_trace.add_stage(svc_stage)
    return [
        svc_stage,
        svc_trace,
        proxy_tracing.StageTrace(
            name="compress",
            enabled=True,
            input_tokens=100,
            output_tokens=80,
            tokens_delta=-20,
            duration_ms=5.0,
            details={"src": "probe"},
        ),
        telemetry_trace.StageTrace(
            name="capsule",
            enabled=True,
            input_tokens=10,
            output_tokens=7,
            tokens_delta=-3,
            details={"src": "probe"},
            duration_ms=1.25,
        ),
        telemetry_rec.Recommendation(
            id="cache.lookup",
            severity="high",
            title="Enable cache lookups",
            evidence={"lookups": 0},
            action="Enable the cache.",
            expected="Lookups become nonzero.",
        ),
    ]


# ---------------------------------------------------------------------------
# Direction 1: base -> new (fixtures created at the prior release load here)
# ---------------------------------------------------------------------------

BASE_FIXTURES = {
    "services_stage_trace.pkl": (
        service_trace.StageTrace,
        {
            "name": "cache",
            "eligible": True,
            "skip_reason": "",
            "applied": False,
            "duration_ms": 0.5,
            "detail": "fixture",
        },
    ),
    "services_optimization_trace.pkl": (
        service_trace.OptimizationTrace,
        {
            "request_id": "fixture-1",
            "mode": "observe",
            "started_at": 1234.5,
            "bypass_reason": "",
            "body_bytes_in": 10,
            "body_bytes_out": 10,
        },
    ),
    "proxy_tracing_stage_trace.pkl": (
        proxy_tracing.StageTrace,
        {
            "name": "compress",
            "enabled": True,
            "input_tokens": 100,
            "output_tokens": 80,
            "tokens_delta": -20,
            "duration_ms": 5.0,
            "details": {"src": "fixture"},
        },
    ),
    "proxy_server_stage_trace.pkl": (
        proxy_tracing.StageTrace,  # server re-exports the tracing class on this tree
        {
            "name": "compress",
            "enabled": True,
            "input_tokens": 100,
            "output_tokens": 80,
            "tokens_delta": -20,
            "duration_ms": 5.0,
            "details": {"src": "fixture"},
        },
    ),
    "telemetry_stage_trace.pkl": (
        telemetry_trace.StageTrace,
        {
            "name": "capsule",
            "enabled": True,
            "input_tokens": 10,
            "output_tokens": 7,
            "tokens_delta": -3,
            "details": {"src": "fixture"},
            "duration_ms": 1.25,
        },
    ),
    "telemetry_recommendation.pkl": (
        telemetry_rec.Recommendation,
        {
            "id": "cache.lookup",
            "severity": "high",
            "title": "Enable cache lookups",
            "evidence": {"lookups": 0},
            "action": "Enable the cache.",
            "expected": "Lookups become nonzero.",
        },
    ),
}


@pytest.mark.parametrize("fixture_name", sorted(BASE_FIXTURES))
def test_base_release_pickle_loads_on_current_tree(fixture_name):
    expected_cls, expected_fields = BASE_FIXTURES[fixture_name]
    data = (FIXTURE_DIR / fixture_name).read_bytes()

    # Fixture integrity: it must reference only historical DTO or stdlib
    # globals — i.e. it is genuinely shaped like a prior-release pickle.
    for ref in _referenced_globals(data):
        assert ref in HISTORICAL_DTO_GLOBALS | STDLIB_PICKLE_GLOBALS, ref

    obj = pickle.loads(data)
    assert type(obj) is expected_cls
    for field_name, expected_value in expected_fields.items():
        assert getattr(obj, field_name) == expected_value


def test_server_module_still_exposes_stage_trace_global():
    # The prior release pickled proxy stage traces under
    # tokenpak.proxy.server.StageTrace as well; that global must keep
    # resolving so those pickles remain loadable.
    from tokenpak.proxy import server

    assert server.StageTrace is proxy_tracing.StageTrace


# ---------------------------------------------------------------------------
# Direction 2: new -> base (pickles made here are loadable after rollback)
# ---------------------------------------------------------------------------


@pytest.mark.parametrize("protocol", list(range(pickle.HIGHEST_PROTOCOL + 1)))
def test_new_pickles_reference_only_historical_globals(protocol):
    for obj in _new_instances():
        data = pickle.dumps(obj, protocol=protocol)
        refs = _referenced_globals(data)
        assert refs, "expected at least one class global in the pickle"
        for ref in refs:
            assert ref in HISTORICAL_DTO_GLOBALS | STDLIB_PICKLE_GLOBALS, (
                f"protocol {protocol} pickle of {type(obj).__qualname__} references "
                f"{ref}, which does not exist at the prior release head"
            )


@pytest.mark.parametrize("protocol", list(range(pickle.HIGHEST_PROTOCOL + 1)))
def test_new_pickles_roundtrip_under_historical_identity(protocol):
    for obj in _new_instances():
        clone = pickle.loads(pickle.dumps(obj, protocol=protocol))
        assert type(clone) is type(obj)
        assert type(clone).__module__ == type(obj).__module__
        assert type(clone).__qualname__ == type(obj).__qualname__
        assert not type(clone).__qualname__.startswith("_")
        assert clone == obj
