# SPDX-License-Identifier: Apache-2.0
"""Auto-scaffolded credential provider modules.

Modules under this package are generated by ``tokenpak adapter
scaffold`` and registered in
``tokenpak/services/routing_service/credential_injector.py`` either
manually (printed instructions in the scaffolder's stdout) or via
``tokenpak adapter scaffold --register`` (in-place insertion).

This package init is intentionally empty — discovery happens through
the registration block in credential_injector.py, not via package
walking.
"""
