#!/usr/bin/env bash
# install-completions.sh — Install TokenPak shell completions
# Supports: bash, zsh, fish
# Usage: bash scripts/install-completions.sh [--dry-run]

set -euo pipefail

DRY_RUN=false
if [[ "${1:-}" == "--dry-run" ]]; then
    DRY_RUN=true
fi

# ── Detect current shell ───────────────────────────────────────────────────────
detect_shell() {
    # Check $SHELL first, fall back to parent process
    if [[ -n "${SHELL:-}" ]]; then
        basename "$SHELL"
    else
        ps -p $PPID -o comm= 2>/dev/null || echo "bash"
    fi
}

CURRENT_SHELL=$(detect_shell)
echo "🐚 Detected shell: ${CURRENT_SHELL}"

# ── Install bash completion ────────────────────────────────────────────────────
install_bash() {
    # Try system directory first, fall back to user directory
    local dest_dirs=(
        "/usr/local/etc/bash_completion.d"
        "/etc/bash_completion.d"
        "${HOME}/.local/share/bash-completion/completions"
        "${HOME}/.bash_completion.d"
    )

    local dest=""
    for d in "${dest_dirs[@]}"; do
        if [[ -d "$d" ]] && [[ -w "$d" ]]; then
            dest="$d/tokenpak"
            break
        fi
    done

    if [[ -z "$dest" ]]; then
        # Create user dir
        mkdir -p "${HOME}/.bash_completion.d"
        dest="${HOME}/.bash_completion.d/tokenpak"
    fi

    echo "  📁 Bash destination: ${dest}"

    if $DRY_RUN; then
        echo "  [dry-run] Would write bash completion to ${dest}"
        return
    fi

    cat > "${dest}" << 'BASH_COMPLETION'
# TokenPak bash completion
# Generated by: tokenpak scripts/install-completions.sh

_tokenpak_commands="activate agent audit auto-optimize benchmark budget calibrate compliance compression config cost dashboard deactivate debug demo diff doctor fingerprint handoff help index last license lock logs macro maintenance metrics optimize plan policy prune recipe replay restart retain route run savings search serve sla start stats status stop template trigger update validate vault version workflow"

_tokenpak_complete() {
    local cur prev words cword
    _init_completion 2>/dev/null || {
        COMPREPLY=()
        cur="${COMP_WORDS[COMP_CWORD]}"
        prev="${COMP_WORDS[COMP_CWORD-1]}"
    }

    # First argument: complete command names
    if [[ ${COMP_CWORD} -eq 1 ]]; then
        COMPREPLY=( $(compgen -W "${_tokenpak_commands}" -- "${cur}") )
        return 0
    fi

    # Sub-command completions
    local cmd="${COMP_WORDS[1]}"
    case "${cmd}" in
        start|serve)
            COMPREPLY=( $(compgen -W "--port --workers --help" -- "${cur}") )
            ;;
        stop|restart)
            COMPREPLY=( $(compgen -W "--help" -- "${cur}") )
            ;;
        status)
            COMPREPLY=( $(compgen -W "--json --help" -- "${cur}") )
            ;;
        logs)
            COMPREPLY=( $(compgen -W "-n --help" -- "${cur}") )
            ;;
        cost|savings|metrics)
            COMPREPLY=( $(compgen -W "--period --json --help" -- "${cur}") )
            ;;
        index)
            COMPREPLY=( $(compgen -W "--status --workers --help" -- "${cur}") )
            ;;
        search)
            COMPREPLY=( $(compgen -W "--limit --json --help" -- "${cur}") )
            ;;
        doctor)
            COMPREPLY=( $(compgen -W "--fix --fleet --help" -- "${cur}") )
            ;;
        config)
            COMPREPLY=( $(compgen -W "sync pull validate --help" -- "${cur}") )
            ;;
        route)
            COMPREPLY=( $(compgen -W "list add remove --model --target --help" -- "${cur}") )
            ;;
        recipe)
            COMPREPLY=( $(compgen -W "list apply create validate test --help" -- "${cur}") )
            ;;
        template)
            COMPREPLY=( $(compgen -W "list add remove apply --help" -- "${cur}") )
            ;;
        budget)
            COMPREPLY=( $(compgen -W "set status reset --limit --help" -- "${cur}") )
            ;;
        benchmark)
            COMPREPLY=( $(compgen -W "--file --sample --json --help" -- "${cur}") )
            ;;
        macro)
            COMPREPLY=( $(compgen -W "list run add remove show --help" -- "${cur}") )
            ;;
        update)
            COMPREPLY=( $(compgen -W "--check --help" -- "${cur}") )
            ;;
        debug)
            COMPREPLY=( $(compgen -W "on off --help" -- "${cur}") )
            ;;
        prune)
            COMPREPLY=( $(compgen -W "--older-than --dry-run --help" -- "${cur}") )
            ;;
        dashboard)
            COMPREPLY=( $(compgen -W "--json --fleet --help" -- "${cur}") )
            ;;
        agent)
            COMPREPLY=( $(compgen -W "status list register deregister --help" -- "${cur}") )
            ;;
        vault)
            COMPREPLY=( $(compgen -W "status encrypt rotate-key --help" -- "${cur}") )
            ;;
        help)
            COMPREPLY=( $(compgen -W "${_tokenpak_commands} --more --all --minimal" -- "${cur}") )
            ;;
        *)
            COMPREPLY=( $(compgen -W "--help" -- "${cur}") )
            ;;
    esac

    return 0
}

complete -F _tokenpak_complete tokenpak
BASH_COMPLETION

    echo "  ✅ Bash completion installed to: ${dest}"

    # Ensure user dir is sourced from .bashrc
    if [[ "$dest" == "${HOME}/.bash_completion.d/tokenpak" ]]; then
        local bashrc="${HOME}/.bashrc"
        local source_line='[ -d ~/.bash_completion.d ] && for f in ~/.bash_completion.d/*; do [ -f "$f" ] && source "$f"; done'
        if ! grep -q "bash_completion.d" "$bashrc" 2>/dev/null; then
            echo "" >> "$bashrc"
            echo "# TokenPak shell completions" >> "$bashrc"
            echo "${source_line}" >> "$bashrc"
            echo "  ✅ Added source line to ${bashrc}"
        fi
    fi
}

# ── Install zsh completion ─────────────────────────────────────────────────────
install_zsh() {
    local dest_dirs=(
        "/usr/local/share/zsh/site-functions"
        "/usr/share/zsh/site-functions"
        "${HOME}/.zsh/completions"
        "${HOME}/.local/share/zsh/completions"
    )

    local dest=""
    for d in "${dest_dirs[@]}"; do
        if [[ -d "$d" ]]; then
            dest="$d/_tokenpak"
            break
        fi
    done

    if [[ -z "$dest" ]]; then
        mkdir -p "${HOME}/.zsh/completions"
        dest="${HOME}/.zsh/completions/_tokenpak"
    fi

    echo "  📁 Zsh destination: ${dest}"

    if $DRY_RUN; then
        echo "  [dry-run] Would write zsh completion to ${dest}"
        return
    fi

    cat > "${dest}" << 'ZSH_COMPLETION'
#compdef tokenpak
# TokenPak zsh completion
# Generated by: tokenpak scripts/install-completions.sh

_tokenpak() {
    local state line
    typeset -A opt_args

    _arguments -C \
        '(-h --help)'{-h,--help}'[Show help]' \
        '1: :_tokenpak_commands' \
        '*:: :->args'

    case $state in
        args)
            case $line[1] in
                start|serve)
                    _arguments \
                        '--port[Port to listen on]:port:' \
                        '--workers[Number of workers]:workers:' \
                        '--help[Show help]'
                    ;;
                status)
                    _arguments \
                        '--json[Output as JSON]' \
                        '--help[Show help]'
                    ;;
                cost|savings|metrics)
                    _arguments \
                        '--period[Time period]:period:(DAY WEEK MONTH)' \
                        '--json[Output as JSON]' \
                        '--help[Show help]'
                    ;;
                index)
                    _arguments \
                        ':directory:_files -/' \
                        '--status[Show indexed file count]' \
                        '--workers[Number of workers]:workers:' \
                        '--help[Show help]'
                    ;;
                search)
                    _arguments \
                        ':query:' \
                        '--limit[Number of results]:limit:' \
                        '--help[Show help]'
                    ;;
                doctor)
                    _arguments \
                        '--fix[Auto-fix issues]' \
                        '--fleet[Check all fleet agents]' \
                        '--help[Show help]'
                    ;;
                config)
                    _arguments \
                        '1: :(sync pull validate)' \
                        '--help[Show help]'
                    ;;
                route)
                    _arguments \
                        '1: :(list add remove)' \
                        '--model[Model name]:model:' \
                        '--help[Show help]'
                    ;;
                budget)
                    _arguments \
                        '1: :(set status reset)' \
                        '--limit[Budget limit]:amount:' \
                        '--help[Show help]'
                    ;;
                macro)
                    _arguments \
                        '1: :(list run add remove show)' \
                        '--help[Show help]'
                    ;;
                debug)
                    _arguments \
                        '1: :(on off)' \
                        '--help[Show help]'
                    ;;
                vault)
                    _arguments \
                        '1: :(status encrypt rotate-key)' \
                        '--help[Show help]'
                    ;;
                help)
                    _arguments \
                        '1: :_tokenpak_commands' \
                        '--more[Show intermediate commands]' \
                        '--all[Show all commands]' \
                        '--minimal[Compact list]'
                    ;;
                *)
                    _arguments '--help[Show help]'
                    ;;
            esac
            ;;
    esac
}

_tokenpak_commands() {
    local commands=(
        'activate:Activate a Pro/Team/Enterprise license key'
        'agent:Agent coordination'
        'audit:Enterprise audit log management'
        'benchmark:Run compression benchmarks'
        'budget:Set API budget limits'
        'calibrate:Calibrate worker count'
        'compliance:Generate compliance reports'
        'compression:Configure compression settings'
        'config:Config sync, pull, validate'
        'cost:View API spend'
        'dashboard:Real-time health dashboard'
        'debug:Toggle verbose debug logging'
        'demo:See compression in action'
        'diff:Show context changes'
        'doctor:Run diagnostics'
        'fingerprint:Fingerprint sync and cache'
        'handoff:Manage agent handoff protocols'
        'help:Show help'
        'index:Index a directory'
        'last:Show last request'
        'license:Show license info'
        'lock:File lock management'
        'logs:Show proxy logs'
        'macro:Manage and run macros'
        'maintenance:Run maintenance tasks'
        'metrics:Show performance metrics'
        'optimize:Analyze efficiency'
        'plan:Show current tier and features'
        'policy:Manage routing policies'
        'prune:Prune old data'
        'recipe:Manage compression recipes'
        'replay:Inspect and re-run sessions'
        'restart:Restart the proxy'
        'retain:Configure retention policies'
        'route:Manage model routing rules'
        'run:Schedule and manage macro runs'
        'savings:Show token and cost savings'
        'search:Search indexed content'
        'serve:Start proxy server (low-level)'
        'sla:Configure SLA targets'
        'start:Start the proxy'
        'stats:Show registry stats'
        'status:Check proxy health'
        'stop:Stop the proxy'
        'template:Manage prompt templates'
        'trigger:Manage event triggers'
        'update:Update TokenPak'
        'validate:Validate a config file'
        'vault:Vault management'
        'version:Show current versions'
        'workflow:Manage workflows'
    )
    _describe 'tokenpak command' commands
}

_tokenpak
ZSH_COMPLETION

    echo "  ✅ Zsh completion installed to: ${dest}"

    # Ensure completions dir is in fpath
    if [[ "$dest" == "${HOME}/.zsh/completions/_tokenpak" ]]; then
        local zshrc="${HOME}/.zshrc"
        if ! grep -q "zsh/completions" "$zshrc" 2>/dev/null; then
            echo "" >> "$zshrc"
            echo "# TokenPak shell completions" >> "$zshrc"
            echo 'fpath=(~/.zsh/completions $fpath)' >> "$zshrc"
            echo "autoload -Uz compinit && compinit" >> "$zshrc"
            echo "  ✅ Added fpath to ${zshrc}"
        fi
    fi
}

# ── Install fish completion ────────────────────────────────────────────────────
install_fish() {
    local dest_dirs=(
        "/usr/share/fish/vendor_completions.d"
        "${HOME}/.config/fish/completions"
    )

    local dest=""
    for d in "${dest_dirs[@]}"; do
        if [[ -d "$d" ]] || [[ "$d" == "${HOME}/.config/fish/completions" ]]; then
            dest="$d/tokenpak.fish"
            break
        fi
    done

    echo "  📁 Fish destination: ${dest}"

    if $DRY_RUN; then
        echo "  [dry-run] Would write fish completion to ${dest}"
        return
    fi

    mkdir -p "$(dirname "${dest}")"

    cat > "${dest}" << 'FISH_COMPLETION'
# TokenPak fish completion
# Generated by: tokenpak scripts/install-completions.sh

set -l commands activate agent audit benchmark budget calibrate compliance compression config cost dashboard deactivate debug demo diff doctor fingerprint handoff help index last license lock logs macro maintenance metrics optimize plan policy prune recipe replay restart retain route run savings search serve sla start stats status stop template trigger update validate vault version workflow

complete -c tokenpak -f -n "not __fish_seen_subcommand_from $commands" -a "$commands"

# Global options
complete -c tokenpak -l help -s h -d "Show help"

# Command-specific options
complete -c tokenpak -n "__fish_seen_subcommand_from start serve" -l port -d "Port to listen on"
complete -c tokenpak -n "__fish_seen_subcommand_from start serve" -l workers -d "Number of workers"
complete -c tokenpak -n "__fish_seen_subcommand_from status" -l json -d "Output as JSON"
complete -c tokenpak -n "__fish_seen_subcommand_from cost savings metrics" -l period -d "Time period (DAY|WEEK|MONTH)"
complete -c tokenpak -n "__fish_seen_subcommand_from cost savings metrics" -l json -d "Output as JSON"
complete -c tokenpak -n "__fish_seen_subcommand_from index" -l status -d "Show indexed file count"
complete -c tokenpak -n "__fish_seen_subcommand_from index" -l workers -d "Number of workers"
complete -c tokenpak -n "__fish_seen_subcommand_from search" -l limit -d "Number of results"
complete -c tokenpak -n "__fish_seen_subcommand_from doctor" -l fix -d "Auto-fix issues"
complete -c tokenpak -n "__fish_seen_subcommand_from doctor" -l fleet -d "Check all fleet agents"
complete -c tokenpak -n "__fish_seen_subcommand_from benchmark" -l file -d "Benchmark a specific file"
complete -c tokenpak -n "__fish_seen_subcommand_from benchmark" -l sample -d "Use sample data"
complete -c tokenpak -n "__fish_seen_subcommand_from benchmark" -l json -d "Output as JSON"
complete -c tokenpak -n "__fish_seen_subcommand_from budget" -l limit -d "Budget limit amount"
complete -c tokenpak -n "__fish_seen_subcommand_from update" -l check -d "Check without installing"
complete -c tokenpak -n "__fish_seen_subcommand_from prune" -l older-than -d "Days threshold"
complete -c tokenpak -n "__fish_seen_subcommand_from prune" -l dry-run -d "Preview only"
complete -c tokenpak -n "__fish_seen_subcommand_from dashboard" -l json -d "Export as JSON"
complete -c tokenpak -n "__fish_seen_subcommand_from dashboard" -l fleet -d "Fleet-wide summary"
complete -c tokenpak -n "__fish_seen_subcommand_from help" -l more -d "Show intermediate commands"
complete -c tokenpak -n "__fish_seen_subcommand_from help" -l all -d "Show all commands"
complete -c tokenpak -n "__fish_seen_subcommand_from help" -l minimal -d "Compact list"
FISH_COMPLETION

    echo "  ✅ Fish completion installed to: ${dest}"
}

# ── Run installations ──────────────────────────────────────────────────────────
echo ""
echo "Installing TokenPak shell completions..."
echo ""

case "${CURRENT_SHELL}" in
    bash)
        install_bash
        ;;
    zsh)
        install_zsh
        ;;
    fish)
        install_fish
        ;;
    *)
        echo "⚠️  Unknown shell: ${CURRENT_SHELL}. Installing for bash and zsh..."
        install_bash
        install_zsh
        ;;
esac

echo ""
if $DRY_RUN; then
    echo "✅ Dry-run complete. No files were written."
else
    echo "✅ Completions installed!"
    echo ""
    echo "To activate in current session:"
    case "${CURRENT_SHELL}" in
        bash)   echo "  source ~/.bashrc" ;;
        zsh)    echo "  exec zsh" ;;
        fish)   echo "  (completions load automatically)" ;;
        *)      echo "  Restart your shell or source your rc file." ;;
    esac
fi
echo ""
