{{- if and .Values.team.enabled .Values.team.persistence.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tokenpak.fullname" . }}-team-vault
  labels:
    {{- include "tokenpak.labels" . | nindent 4 }}
    app.kubernetes.io/component: team
spec:
  accessModes:
    - {{ .Values.team.persistence.accessMode }}
  {{- $sc := .Values.team.persistence.storageClass | default .Values.global.storageClass }}
  {{- if $sc }}
  storageClassName: {{ $sc }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.team.persistence.size }}
{{- end }}
